# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog
author:
  email: mtask.gh@protonmail.com
  name: mtask
description: 'cybersecurity, homelab tinkering, etc.'
#baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: mtask
gpg: 
  pub: '/files/publickey.mtask.gh@protonmail.com.asc'
  fingerprint: '8949b98a4e63585fe3bf6a953b9fd3e9ad04482e (gpg)'
# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-console
#remote_theme: b2a3e8/jekyll-theme-console
#remote_theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
future: true
header_pages:
  - 'index.md'
  - 'about.md'
  - 'categories.md'
  - 'random.md'
minima:
  skin: dark
  social_links:
    github: mtask

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
